export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Landform',
    headline: 'Granabeg, Wicklow',
    description: 'Our operations in this granite quarry began in 1992. We have been in the business for 30 years and have reserves of over 900,000 tonne’s of top quality granite. Since then we have supplied granite to both private businesses & state entities. ',
    buttonLabel: 'Inquire now',
    imgStart: false,
    img: require('../../images/quarry.jpg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Quality Granite',
    headline: 'Straight from the Wicklow Mountains',
    description: 'The term “Wicklow White Granite” arises from the dominance of pale grey quartz & a milky white feldspar grain with a slight alignment of dark mica which makes it paler than normal grey granites. When cut & polished the colour is soft & pleasing hence the market demand.',
    buttonLabel: 'Inquire now',
    imgStart: true,
    img: require('../../images/svg-5.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjThree = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Our Impact',
    headline: 'Supplying granite to all of Ireland',
    description: 'Granite from our quarry has been used for centuries in famous Irish landmarks such as Dublin Castle, The GPO, the Four Courts, Trinity College, the Ha’penny Bridge in Dublin, Powerscourt House in Wicklow and kerbing all around Dublin city – if you are in Dublin City you will see our granite. The American Embassy, Ballsbridge, Dublin 4 has our reconstituted granite & cut granite on the perimeter wall for the past 22 years without any deterioration.',
    buttonLabel: 'Inquire now',
    imgStart: false,
    img: require('../../images/svg-6.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
};
