export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Landform',
    headline: 'Granabeg, Wicklow',
    description: 'Our operations in this granite quarry began in 1992. We have been in the business for 30 years and have reserves of over 900,000 tonne’s of top quality granite. Since then we have supplied granite to both private businesses & state entities. ',
    buttonLabel: 'Inquire now',
    imgStart: false,
    img: require('../../images/quarry.jpg').default,
    alt: 'Photo from our Quarry',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Quality Granite',
    headline: 'Straight from the Wicklow Mountains',
    description: 'The term “Wicklow White Granite” arises from the dominance of pale grey quartz & a milky white feldspar grain with a slight alignment of dark mica which makes it paler than normal grey granites. When cut & polished the colour is soft & pleasing hence the market demand.',
    buttonLabel: 'Inquire now',
    imgStart: true,
    img: require('../../images/granitecloseup.jpg').default,
    alt: 'Close up of granite',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjThree = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Our Impact',
    headline: 'Supplying granite to all of Ireland',
    description: 'Granite from our quarry has been used for centuries in famous Irish landmarks such as Dublin Castle, The GPO, the Four Courts, Trinity College, the Ha’penny Bridge in Dublin, Powerscourt House in Wicklow and kerbing all around Dublin city. The American Embassy, Ballsbridge, Dublin 4 has our reconstituted granite & cut granite on the perimeter wall for the past 22 years without any deterioration. Our granite has also been used overseas in London at the Four Seasons Hotel at Ten Trinity Square.',
    buttonLabel: 'Inquire now',
    imgStart: false,
    img: require('../../images/trinitysquare.jpg').default,
    alt: 'Our Granite in Trinity Square',
    dark: true,
    primary: true,
    darkText: false,
};
